#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux, only do this on server running tmux
if [ -S "$SSH_AUTH_SOCK" ] ; then
    HOST=$(hostname)
    if [ "$HOST" = "editsb" ] || [ "$HOST" = "cmpsb" ] ; then
        ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
    fi
fi